### ISSUE TITLE
The NIM pretrained weights

### ISSUE THREAD

**Issue by Tsai-chia-hsiang** [youzunzhi/NIM-AdvDef#2]
Hi, could I ask the pretrained weights for NIM to reproduce the result ? Thanks.

**Comment by youzunzhi** [comment]
Hello. Thank you for your interest. Here is an NIM-MAE pretrained model with $\sigma \sim \Gamma(25, 3)$: [https://drive.google.com/file/d/1jDtXE7w_eSxlauKh8tzTYUuG2rNeszxR/view?usp=drive_link](https://drive.google.com/file/d/1jDtXE7w_eSxlauKh8tzTYUuG2rNeszxR/view?usp=drive_link).
